# Generated by Django 4.2.6 on 2023-10-14 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('tiempo', models.CharField(blank=True, max_length=10, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=10, null=True)),
                ('porciones', models.IntegerField()),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('img', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
