# Generated by Django 4.2.6 on 2023-10-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_recetas_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='img',
        ),
        migrations.AlterField(
            model_name='recetas',
            name='dificultad',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Media', 'Media'), ('Dificil', 'Dificil')], default='Facil', max_length=10),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='porciones',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tiempo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
