# Generated by Django 4.2.6 on 2023-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_recetas_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='tiempo',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
